# Generated by Django 5.0 on 2024-06-21 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('staff_number', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('dateOf_Uni_Appointment', models.DateField(default=datetime.date.today)),
                ('presentUni_bungalow', models.CharField(max_length=100)),
                ('date_of_occupation_ofAccomodation', models.DateField(blank=True, null=True)),
                ('studyLeave_from', models.DateField(blank=True, null=True)),
                ('studyLeave_to', models.DateField(blank=True, null=True)),
                ('initial_point', models.IntegerField(default=0)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('none', 'None')], default='Single', max_length=50)),
                ('duty_status', models.CharField(choices=[('provert', 'Provert'), ('deans', 'Deans'), ('head of department', 'Head of Department')], default='Provert', max_length=50)),
                ('num_of_children', models.IntegerField()),
                ('date_of_duty', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='status_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100)),
                ('point', models.IntegerField()),
            ],
        ),
    ]
