# Generated by Django 5.0 on 2024-06-26 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='present_accommodation',
            field=models.CharField(choices=[('off_campus', 'Off Campus'), ('on_campus', 'On Campus'), ('temporary_accommodation', 'Temporary Accommodation'), ('not_accommodated', 'Not Accommodated')], default='Not Accomodated', max_length=50),
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_a', models.CharField(blank=True, max_length=255, null=True)),
                ('preference_b', models.CharField(blank=True, max_length=255, null=True)),
                ('preference_c', models.CharField(blank=True, max_length=255, null=True)),
                ('preference_d', models.CharField(blank=True, max_length=255, null=True)),
                ('preference_e', models.CharField(blank=True, max_length=255, null=True)),
                ('preference_f', models.CharField(blank=True, max_length=255, null=True)),
                ('preference_g', models.CharField(blank=True, max_length=255, null=True)),
                ('preference_h', models.CharField(blank=True, max_length=255, null=True)),
                ('preference_i', models.CharField(blank=True, max_length=255, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='project.appointment')),
            ],
        ),
    ]
