# Generated by Django 5.0 on 2024-08-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_appointment_present_accommodation_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('senior_member', 'Senior Member'), ('senior_staff', 'Senior Staff'), ('junior_staff', 'Junior Staff')], max_length=50)),
                ('vacant_rooms', models.IntegerField()),
            ],
        ),
    ]
