# Generated by Django 5.0 on 2024-08-20 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='preference_a',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_b',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_c',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_d',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_e',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_f',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_g',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_h',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_i',
        ),
        migrations.AddField(
            model_name='preference',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='preference',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='project.appointment'),
        ),
    ]
