# Generated by Django 5.0 on 2024-08-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_preference_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='preference_a',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_b',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_c',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_d',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_e',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_f',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_g',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_h',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preference_i',
        ),
        migrations.AddField(
            model_name='preference',
            name='preference',
            field=models.CharField(default='junior_staff', max_length=255),
        ),
    ]
