# Generated by Django 5.0 on 2024-08-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_preference_preference_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='preference',
            field=models.CharField(default='ff1', max_length=255),
        ),
    ]
