# Generated by Django 5.0 on 2024-08-27 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_designation_point_senior_staff_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign_point_and_preference_senior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_assigned', models.CharField(blank=True, max_length=255, null=True)),
                ('total_points', models.IntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_point_and_preference_set', to='project.senior_staff_appointment')),
            ],
        ),
    ]
